# Copyright 2026 Sumith Ramsookbhai. Licensed under Apache-2.0 (see LICENSE).
from sumo_qa.server import build_mcp_server

# Phase 4 slimmed surface: 4 test-data tools + 6 knowledge loaders = 10 atomic tools.
# Phase 5 follow-up: each SKILL.md is also registered as an MCP tool
# (in addition to its MCP prompt) so hosts whose slash menus surface tools but
# not prompts (IntelliJ AI Assistant, VS Code + Copilot) can invoke skills.
# Chain-polish pass added 3 more skills (planning / executing / finishing).
# Task 8: sumo-qa-suggesting-external-skill added.
# External-skill lifecycle restored as thin MCP tools; Node installer helpers remain deleted.
# Task 72: sumo_qa_load_specialty_tools removed (catalogue → discovery rule).
# Issue #144: sumo_qa_format_risk_ledger added (risk-to-test ledger formatter).
# Issue #145: sumo_qa_capture_review_feedback added (review-feedback memory).
# Issue #146: sumo-qa-closing-qa-gaps added (closed-loop regression workflow skill).
# The registered surface is two kinds of tool: the atomic @mcp.tool decorators
# (enumerated by the _*_TOOL_NAMES groups below) and one filesystem-driven
# skill-prompt tool per skills/<name>/SKILL.md (the _SKILL_TOOL_NAMES group).
# There is no hand-maintained total here on purpose (issue #352): the canonical
# count is whatever build_mcp_server() registers. That live count is pinned by
# tests/test_e2e_mcp_initialize.py::test_mcp_tools_list_count_matches_registry,
# which asserts the subprocess-advertised count equals the in-process
# build_mcp_server() registry count. The committed
# tests/fixtures/mcp_tools_list_snapshot.json (regenerated by
# scripts/regen_tools_list_snapshot.py) is a separate required-tools-present +
# schema contract (tests/test_tools_list_contract.py, a superset contract) —
# it does NOT pin the count. The atomic subset is the single source of truth
# derived in installer.REQUIRED_TOOL_NAMES.
_TEST_DATA_TOOL_NAMES = {
    "sumo_qa_explain_test_data_requirements",
    "sumo_qa_find_test_data",
    "sumo_qa_validate_test_data",
    "sumo_qa_register_known_good_test_data",
}

_INGESTION_TOOL_NAMES = {
    "sumo_qa_ingest_knowledge_pack",
}

# Explicit review-feedback memory (issue #145). Writer-local; nothing is
# persisted without an explicit user-confirmed capture, and memory-derived
# probes are advisory (never override canonical classifications/rules).
_FEEDBACK_MEMORY_TOOL_NAMES = {
    "sumo_qa_capture_review_feedback",
}

_CAPABILITIES_TOOL_NAMES = {
    "sumo_qa_capabilities",
}

# Repo-map artifact tools (issue #155 slice 3 — host-callable wrapper around
# the slice-2 deterministic scanner). Compact-summary response by design;
# the full artifact is only returned via the optional `write_to` path.
_REPO_MAP_TOOL_NAMES = {
    "sumo_qa_scan_repo",
    "sumo_qa_analyze_diff_impact",
    "sumo_qa_query_repo_map",
}

# Risk-to-test traceability ledger formatter (issue #144). File/format plumbing
# only — validates host-supplied risk rows and renders the markdown appendix; it
# performs no risk inference.
_LEDGER_TOOL_NAMES = {
    "sumo_qa_format_risk_ledger",
}

_CONTEXT_BUNDLE_TOOL_NAMES = {
    "sumo_qa_format_context_bundle",
}

_SCORECARD_TOOL_NAMES = {
    "sumo_qa_format_qa_scorecard",
}

_EXPORT_TOOL_NAMES = {
    "sumo_qa_export_test_cases",
}

# Local QA report (issue #157). Composes the persisted .sumo-qa artifacts into
# a static HTML page; compact readiness summary in the response, the page body
# only on disk via write_to.
_QA_REPORT_TOOL_NAMES = {
    "sumo_qa_generate_qa_report",
}

# Progressive skill loading (issue #285) — deterministic, read-only, local-only
# manifest index + partial skill-context loader. The existing zero-argument
# skill tools still return full bodies unchanged; these add a slice-loading path.
_SKILL_LOADING_TOOL_NAMES = {
    "sumo_qa_list_skill_manifests",
    "sumo_qa_load_skill_context",
}

_KNOWLEDGE_LOADER_TOOL_NAMES = {
    "sumo_qa_load_classifications",
    "sumo_qa_load_approaches",
    "sumo_qa_load_principles",
    "sumo_qa_load_techniques",
    "sumo_qa_load_standards",
    "sumo_qa_load_rules",
    "sumo_qa_load_catalogue_entry",
}

_EXTERNAL_SKILL_TOOL_NAMES = {
    "sumo_qa_search_external_skills",
    "sumo_qa_check_external_skill_installed",
    "sumo_qa_install_external_skill",
    "sumo_qa_execute_external_skill",
}

# Skills registered as MCP tools (parallel to their MCP-prompt registration).
# Names match the skill directory with `-` -> `_`.
_SKILL_TOOL_NAMES = {
    "using_sumo_qa",
    "sumo_qa_deciding_approach",
    "sumo_qa_preparing_for_work",
    "sumo_qa_creating_test_plan",
    "sumo_qa_implementing_with_tdd",
    "sumo_qa_reviewing_before_merge",
    "sumo_qa_strengthening_tests",
    "sumo_qa_finding_test_data",
    "sumo_qa_answering_testing_question",
    "sumo_qa_strategising",
    # Chain-polish pass: planning + executing + finishing skills.
    "sumo_qa_planning_qa_rollout",
    "sumo_qa_executing_qa_rollout",
    "sumo_qa_finishing_qa_work",
    # Task 8: external-skill suggestion.
    "sumo_qa_suggesting_external_skill",
    # Issue #146: closed-loop regression workflow.
    "sumo_qa_closing_qa_gaps",
}

# Heavy tools that MUST NOT be registered after Phase 4. The skills now drive
# this work via SKILL.md prompts + the knowledge_loader tools.
_HEAVY_TOOL_NAMES_DELETED = {
    "sumo_qa_prepare_for_work",
    "sumo_qa_review_local_change",
    "sumo_qa_answer_testing_question",
    "sumo_qa_create_test_plan",
    "sumo_qa_scaffold_tests",
    "sumo_qa_decide_approach",
    "sumo_qa_get_external_skill_info",
    "sumo_qa_load_external_skills_registry",
    "sumo_qa_check_node_available",
    "sumo_qa_detect_node_installer",
    "sumo_qa_install_node",
}


def test_builds_mcp_server_with_registered_tools() -> None:
    server = build_mcp_server()

    assert type(server).__name__ == "FastMCP"


_ATOMIC_TOOL_NAME_GROUPS = (
    _TEST_DATA_TOOL_NAMES
    | _KNOWLEDGE_LOADER_TOOL_NAMES
    | _CAPABILITIES_TOOL_NAMES
    | _REPO_MAP_TOOL_NAMES
    | _LEDGER_TOOL_NAMES
    | _CONTEXT_BUNDLE_TOOL_NAMES
    | _SCORECARD_TOOL_NAMES
    | _EXPORT_TOOL_NAMES
    | _QA_REPORT_TOOL_NAMES
    | _INGESTION_TOOL_NAMES
    | _FEEDBACK_MEMORY_TOOL_NAMES
    | _EXTERNAL_SKILL_TOOL_NAMES
    | _SKILL_LOADING_TOOL_NAMES
)


def test_registers_only_test_data_knowledge_and_skill_tools() -> None:
    server = build_mcp_server()

    tool_names = set(server._tool_manager._tools.keys())

    assert tool_names == (_ATOMIC_TOOL_NAME_GROUPS | _SKILL_TOOL_NAMES)


def test_atomic_tool_groups_match_derived_single_source_of_truth() -> None:
    """The human-readable atomic name groups in THIS file must equal the
    single source of truth derived in installer.REQUIRED_TOOL_NAMES (issue
    #352). Without this cross-check the documentation groups here and the
    derived constant could silently diverge — the exact drift the SSOT change
    set out to eliminate. If this fails, the live registry changed: update the
    _*_TOOL_NAMES groups above (the constant re-derives itself)."""
    from sumo_qa import installer

    assert _ATOMIC_TOOL_NAME_GROUPS == set(installer.REQUIRED_TOOL_NAMES)


def test_skills_registered_as_tools_only() -> None:
    """Each SKILL.md is registered as an MCP tool, NOT as a prompt.

    Single delivery channel rationale: MCP tools are surfaced in the
    slash menu by Claude Code, IntelliJ AI Assistant, and VS Code +
    Copilot — registering as tools alone gives identical slash-menu
    behavior across hosts. Registering as both creates duplicate
    entries in Claude Code and is the confusion this design avoids."""
    server = build_mcp_server()
    tool_names = set(server._tool_manager._tools.keys())
    prompt_names = set(server._prompt_manager._prompts.keys())

    assert _SKILL_TOOL_NAMES.issubset(tool_names), (
        f"Missing skill tools: {_SKILL_TOOL_NAMES - tool_names}"
    )
    assert _SKILL_TOOL_NAMES.isdisjoint(prompt_names), (
        f"Skill names leaked into prompts: {_SKILL_TOOL_NAMES & prompt_names}"
    )


def test_no_heavy_tools_leak_after_phase_4_deletion() -> None:
    """Defensive guard: the 6 heavy reasoning tools were deleted in Phase 4.
    If any of them re-appear in the registered surface a future change is
    accidentally re-introducing the heavy single-shot path."""
    server = build_mcp_server()
    tool_names = set(server._tool_manager._tools.keys())
    leaked = tool_names & _HEAVY_TOOL_NAMES_DELETED
    assert not leaked, f"Heavy tools leaked back into the registered surface: {leaked}"


def test_tool_descriptions_advertise_natural_language_triggers() -> None:
    server = build_mcp_server()
    tools = server._tool_manager._tools

    find_data = tools["sumo_qa_find_test_data"].description
    assert "find me test data" in find_data.lower()


def test_tool_descriptions_avoid_directive_language() -> None:
    """Tool descriptions must NOT contain instructions aimed at the model.

    Directive phrases like 'Use this when...' look like prompt-injection to
    defensive hosts (e.g. IntelliJ AI Assistant). Descriptions should be
    declarative ('Returns ...', 'Generates ...') with natural-language triggers
    framed as facts about the tool, not instructions to the caller.
    """
    server = build_mcp_server()
    forbidden_phrases = [
        "use this when",
        "use this before",
        "use this if",
        "you must",
        "you should",
        "ignore previous",
    ]
    for name, tool in server._tool_manager._tools.items():
        description = (tool.description or "").lower()
        for phrase in forbidden_phrases:
            assert phrase not in description, (
                f"tool {name!r} description contains directive phrase {phrase!r}; "
                "rewrite as a declarative description of what the tool returns."
            )


def test_knowledge_loader_tools_are_registered():
    """The 6 sumo_qa_load_* tools must appear in the server's tool list."""
    server = build_mcp_server()
    tool_names = set(server._tool_manager._tools.keys())
    for name in _KNOWLEDGE_LOADER_TOOL_NAMES:
        assert name in tool_names, f"Missing tool: {name}"


def _tool_text(result) -> str:
    if isinstance(result, str):
        return result
    if isinstance(result, list):
        return "\n".join(getattr(item, "text", str(item)) for item in result)
    return getattr(result, "text", str(result))


def test_filtered_knowledge_loader_args_are_forwarded_via_server_call_tool() -> None:
    """The MCP-facing wrappers must pass classification filters through."""
    import asyncio

    server = build_mcp_server()

    async def run() -> tuple[str, str]:
        standards = await server.call_tool(
            "sumo_qa_load_standards",
            {"classification": "api_contract_change, business_logic_change"},
        )
        rules = await server.call_tool(
            "sumo_qa_load_rules", {"classification": "frontend_change config_change"}
        )
        return _tool_text(standards), _tool_text(rules)

    standards_text, rules_text = asyncio.run(run())

    assert "QA Shift-Left Core Standards" in standards_text
    assert "ISTQB-Aligned Senior QA Standards" not in standards_text
    assert "frontend_change:" in rules_text
    assert "config_change:" in rules_text
    assert "ui_only_change:" not in rules_text
    assert "configuration_change:" not in rules_text


def test_skill_loading_tools_return_json_via_call_tool() -> None:
    """The #285 MCP wrappers must JSON-serialise the manifest + loader output."""
    import asyncio
    import json

    server = build_mcp_server()

    def _text(result) -> str:
        # call_tool returns (content_list, structured_result); the JSON string
        # this tool emits is the text of the first content block.
        content = result[0] if isinstance(result, tuple) else result
        return _tool_text(content)

    async def run() -> tuple[str, str]:
        manifests = await server.call_tool("sumo_qa_list_skill_manifests", {})
        full = await server.call_tool(
            "sumo_qa_load_skill_context",
            {"skill_name": "using-sumo-qa", "mode": "manifest"},
        )
        return _text(manifests), _text(full)

    manifests_text, manifest_text = asyncio.run(run())

    manifests = json.loads(manifests_text)
    assert {m["skill_name"] for m in manifests["skills"]}  # non-empty
    loaded = json.loads(manifest_text)
    assert loaded["skill_name"] == "using-sumo-qa"
    assert loaded["mode"] == "manifest"


def test_list_skill_manifests_detail_via_call_tool() -> None:
    """#306: the MCP wrapper defaults to compact (no sections[]/modules[]) and
    returns the full index only on explicit detail="full_index"; an invalid
    detail comes back as an error envelope, not a raised ToolError."""
    import asyncio
    import json

    server = build_mcp_server()

    def _text(result) -> str:
        content = result[0] if isinstance(result, tuple) else result
        return _tool_text(content)

    async def run() -> tuple[str, str, str]:
        default = await server.call_tool("sumo_qa_list_skill_manifests", {})
        full = await server.call_tool("sumo_qa_list_skill_manifests", {"detail": "full_index"})
        bad = await server.call_tool("sumo_qa_list_skill_manifests", {"detail": "compact_index"})
        return _text(default), _text(full), _text(bad)

    default_text, full_text, bad_text = asyncio.run(run())

    default = json.loads(default_text)
    assert default["skills"], "expected at least one bundled skill"
    assert all("sections" not in m and "modules" not in m for m in default["skills"])

    full = json.loads(full_text)
    assert all("sections" in m and "modules" in m for m in full["skills"])

    bad = json.loads(bad_text)
    assert "error" in bad
    assert bad["available_detail"] == ["compact", "full_index"]
    assert "skills" not in bad


# ---------------------------------------------------------------------------
# __main__ module import (covers sumo_qa/__main__.py:2)
# ---------------------------------------------------------------------------


def test_main_module_imports_without_error() -> None:
    """Importing sumo_qa.__main__ must not raise — it just wires main()."""
    import importlib

    mod = importlib.import_module("sumo_qa.__main__")
    assert hasattr(mod, "main")


# ---------------------------------------------------------------------------
# Tool bodies — call the registered MCP tools directly via the server so the
# nested function bodies inside build_mcp_server() are executed.
# ---------------------------------------------------------------------------


def test_tool_bodies_are_reachable_via_server_call_tool() -> None:
    """Calling each test-data tool via the server exercises the inner function
    bodies that are registered at build time but not called by structural tests."""
    import asyncio
    from pathlib import Path

    from sumo_qa.tdm_catalogue import TestDataCatalogue
    from sumo_qa.tools import QAShiftLeftService

    service = QAShiftLeftService(
        test_data_catalogue=TestDataCatalogue(
            Path(__file__).resolve().parent / "fixtures" / "test_data"
        )
    )
    server = build_mcp_server(service=service)

    async def run_tools() -> list:
        results = []
        # sumo_qa_explain_test_data_requirements (lines 125-138)
        r = await server.call_tool(
            "sumo_qa_explain_test_data_requirements", {"question": "what data for login?"}
        )
        results.append(r)
        # sumo_qa_find_test_data (lines 181-208)
        r = await server.call_tool(
            "sumo_qa_find_test_data", {"environment": "integration", "domain": "auth"}
        )
        results.append(r)
        # sumo_qa_validate_test_data (lines 225-237)
        r = await server.call_tool(
            "sumo_qa_validate_test_data", {"entry_id": "auth-locked-account-001"}
        )
        results.append(r)
        # sumo_qa_load_classifications (line 276)
        r = await server.call_tool("sumo_qa_load_classifications", {})
        results.append(r)
        # sumo_qa_load_approaches (line 282)
        r = await server.call_tool("sumo_qa_load_approaches", {})
        results.append(r)
        # sumo_qa_load_principles (line 288)
        r = await server.call_tool("sumo_qa_load_principles", {})
        results.append(r)
        # sumo_qa_load_techniques (line 295)
        r = await server.call_tool("sumo_qa_load_techniques", {})
        results.append(r)
        # sumo_qa_load_standards (line 312)
        r = await server.call_tool("sumo_qa_load_standards", {})
        results.append(r)
        # sumo_qa_load_rules (line 318)
        r = await server.call_tool("sumo_qa_load_rules", {})
        results.append(r)
        # sumo_qa_load_catalogue_entry — whole-catalogue branch (name omitted)
        r = await server.call_tool(
            "sumo_qa_load_catalogue_entry",
            {"catalogue": "classifications", "format": "compact"},
        )
        results.append(r)
        # sumo_qa_load_catalogue_entry — single-entry branch (name set)
        r = await server.call_tool(
            "sumo_qa_load_catalogue_entry",
            {"catalogue": "classifications", "name": "api_contract_change"},
        )
        results.append(r)
        return results

    results = asyncio.run(run_tools())
    assert len(results) == 11


def test_tool_body_register_known_good_via_server(tmp_path) -> None:
    """sumo_qa_register_known_good_test_data body (lines 253-264)."""
    import asyncio

    from sumo_qa.tdm_catalogue import TestDataCatalogue
    from sumo_qa.tools import QAShiftLeftService

    service = QAShiftLeftService(test_data_catalogue=TestDataCatalogue(tmp_path / "test_data"))
    server = build_mcp_server(service=service)

    async def run():
        return await server.call_tool(
            "sumo_qa_register_known_good_test_data",
            {
                "entry": {
                    "id": "auth-server-test-001",
                    "environment": "integration",
                    "domain": "auth",
                    "scenario_tags": ["active_account"],
                    "known_valid_for": ["login flow"],
                    "owner": "qa",
                    "confidence": "medium",
                    "source": "qa-curated",
                }
            },
        )

    result = asyncio.run(run())
    assert result is not None


def test_tool_body_error_envelope_on_explain_failure() -> None:
    """Exception path in sumo_qa_explain_test_data_requirements body (line 128)."""
    import asyncio
    from unittest.mock import MagicMock

    async def run():
        # Build a server with a broken service to exercise the exception envelope path.
        broken_service = MagicMock()
        broken_service.qa_explain_test_data_requirements.side_effect = RuntimeError("broken")
        s = build_mcp_server(service=broken_service)
        return await s.call_tool("sumo_qa_explain_test_data_requirements", {"question": "x"})

    result = asyncio.run(run())
    assert result is not None


def test_tool_body_error_envelope_on_find_failure() -> None:
    """Exception path in sumo_qa_find_test_data body (line 193)."""
    import asyncio
    from unittest.mock import MagicMock

    broken_service = MagicMock()
    broken_service.qa_find_test_data.side_effect = RuntimeError("broken find")
    server = build_mcp_server(service=broken_service)

    async def run():
        return await server.call_tool("sumo_qa_find_test_data", {})

    result = asyncio.run(run())
    assert result is not None


def test_tool_body_error_envelope_on_validate_failure() -> None:
    """Exception path in sumo_qa_validate_test_data body (line 228)."""
    import asyncio
    from unittest.mock import MagicMock

    broken_service = MagicMock()
    broken_service.qa_validate_test_data.side_effect = RuntimeError("broken validate")
    server = build_mcp_server(service=broken_service)

    async def run():
        return await server.call_tool("sumo_qa_validate_test_data", {})

    result = asyncio.run(run())
    assert result is not None


def test_tool_body_error_envelope_on_register_failure() -> None:
    """Exception path in sumo_qa_register_known_good_test_data body (line 256)."""
    import asyncio
    from unittest.mock import MagicMock

    broken_service = MagicMock()
    broken_service.qa_register_known_good_test_data.side_effect = RuntimeError("broken register")
    server = build_mcp_server(service=broken_service)

    async def run():
        return await server.call_tool(
            "sumo_qa_register_known_good_test_data", {"entry": {"id": "x"}}
        )

    result = asyncio.run(run())
    assert result is not None


def test_main_function_runs_server() -> None:
    """server.main() calls build_mcp_server().run() — covers line 326."""
    from unittest.mock import MagicMock, patch

    mock_server = MagicMock()
    with patch("sumo_qa.server.build_mcp_server", return_value=mock_server):
        from sumo_qa.server import main

        main()

    mock_server.run.assert_called_once()


def test_build_mcp_server_raises_when_mcp_not_installed() -> None:
    """ImportError path in build_mcp_server() (lines 73-74)."""
    import sys
    from unittest.mock import patch

    with patch.dict(sys.modules, {"mcp.server.fastmcp": None, "mcp.types": None}):
        import pytest

        with pytest.raises((RuntimeError, ImportError)):
            build_mcp_server()


def test_server_instructions_enforce_qa_routing() -> None:
    """FastMCP `instructions=` must carry the routing directive so hosts
    that surface server-level instructions (not just repo files) see the
    rule at session start."""
    server = build_mcp_server()
    text = getattr(server, "instructions", "") or ""
    assert "ROUTING DIRECTIVE" in text, (
        "FastMCP instructions lost the ROUTING DIRECTIVE header (#238)."
    )
    assert "sumo_qa_using_sumo_qa" in text, (
        "FastMCP instructions must name the entry router `sumo_qa_using_sumo_qa`."
    )
    # Forbids silent supplementation from training data.
    assert "sumo_qa_load_" in text, (
        "FastMCP instructions must require `sumo_qa_load_*` for citing "
        "principles/techniques/classifications/approaches."
    )


def test_copilot_instructions_enforce_qa_routing() -> None:
    """`.github/copilot-instructions.md` must carry the Hard rule so VS Code
    + Copilot honours the routing directive without depending on the MCP
    server being loaded first."""
    from pathlib import Path

    repo_root = Path(__file__).resolve().parent.parent
    text = (repo_root / ".github" / "copilot-instructions.md").read_text(encoding="utf-8")
    assert "Hard rule" in text, "copilot-instructions.md lost the Hard rule header."
    assert "sumo_qa_using_sumo_qa" in text, (
        "copilot-instructions.md must name the entry router `sumo_qa_using_sumo_qa`."
    )
    assert "sumo_qa_load_" in text, (
        "copilot-instructions.md must require `sumo_qa_load_*` for citations."
    )


def test_using_sumo_qa_skill_carries_iron_law() -> None:
    """The entry-router skill body must keep the Iron Law verbatim — every
    sub-skill inherits its discipline from this anchor."""
    from pathlib import Path

    repo_root = Path(__file__).resolve().parent.parent
    text = (repo_root / "skills" / "using-sumo-qa" / "SKILL.md").read_text(encoding="utf-8")
    assert "NO QA WORK WITHOUT FIRST DECIDING THE APPROACH" in text, (
        "using-sumo-qa SKILL.md lost the Iron Law (#238)."
    )
    assert "sumo-qa-deciding-approach" in text, (
        "using-sumo-qa SKILL.md must still route to `sumo-qa-deciding-approach` (#238)."
    )
