# Copyright 2026 Sumith Ramsookbhai. Licensed under Apache-2.0 (see LICENSE).
"""Tests for the committed marketplace assets (issue #84).

The assets are GENERATED by scripts/generate_marketplace_assets.py and
committed; these tests pin the acceptance criteria without adding any
imaging dependency:

  T1 — assets/icon-512.png is a valid PNG and exactly 512x512 (IHDR parse)
  T2 — icon stays under the repo's 500 KB added-file ceiling
  T3 — assets/preview-doctor.svg is well-formed XML with positive dimensions
  T4 — preview shows REAL doctor output (capture + render agree on content)
  T5 — sanitisation held: no absolute home paths leak into committed assets
  T6 — brand rule: no emoji/pictogram codepoints in the text assets
"""

from __future__ import annotations

import re
import struct
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ICON = REPO_ROOT / "assets" / "icon-512.png"
CAPTURE = REPO_ROOT / "assets" / "preview-doctor.txt"
PREVIEW = REPO_ROOT / "assets" / "preview-doctor.svg"

_PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"


def _png_dimensions(path: Path) -> tuple[int, int]:
    blob = path.read_bytes()
    assert blob[:8] == _PNG_SIGNATURE, f"{path} lacks a PNG signature"
    assert blob[12:16] == b"IHDR", f"{path} first chunk is not IHDR"
    width, height = struct.unpack(">II", blob[16:24])
    return width, height


def test_icon_is_512_square() -> None:
    """T1 — the marketplace icon is exactly 512x512."""
    assert ICON.is_file(), (
        "assets/icon-512.png missing — run scripts/generate_marketplace_assets.py icon"
    )
    assert _png_dimensions(ICON) == (512, 512)


def test_icon_under_large_file_ceiling() -> None:
    """T2 — stays under the pre-commit check-added-large-files 500 KB cap."""
    assert ICON.stat().st_size < 500 * 1024


def test_preview_svg_declares_dimensions() -> None:
    """T3 — the preview opens with an <svg> root that declares positive
    dimensions. Parsed with a regex, not an XML library: the file is
    repo-generated, and stdlib XML parsers are XXE-prone on principle."""
    text = PREVIEW.read_text(encoding="utf-8")
    match = re.match(r'<svg [^>]*width="(\d+)" height="(\d+)"', text)
    assert match, "preview-doctor.svg does not open with a dimensioned <svg> root"
    width, height = int(match.group(1)), int(match.group(2))
    assert width >= 800, "preview should be presentation-sized"
    assert height > 0
    assert text.rstrip().endswith("</svg>")
    assert "<!ENTITY" not in text and "<!DOCTYPE" not in text


def test_preview_renders_real_doctor_output() -> None:
    """T4 — every doctor check line in the committed capture appears in the
    rendered SVG (the preview is a render of real output, not a mockup)."""
    capture = CAPTURE.read_text(encoding="utf-8")
    svg = PREVIEW.read_text(encoding="utf-8")
    status_lines = [
        line for line in capture.splitlines() if line.startswith(("[OK]", "[WARN]", "[FAIL]"))
    ]
    assert status_lines, "capture has no doctor status lines — refresh via capture mode"
    for line in status_lines:
        check_id = line.split("—")[0].strip()
        assert check_id in svg, f"capture line not rendered: {check_id}"
    assert "Summary:" in capture and "Summary:" in svg


def test_assets_contain_no_machine_paths() -> None:
    """T5 — path sanitisation held (privacy + reproducible regeneration)."""
    for path in (CAPTURE, PREVIEW):
        text = path.read_text(encoding="utf-8")
        assert "/Users/" not in text, f"{path.name} leaks an absolute macOS home path"
        assert "C:\\Users" not in text, f"{path.name} leaks an absolute Windows home path"
        assert "/home/" not in text, f"{path.name} leaks an absolute Linux home path"


def test_text_assets_contain_no_pictograms() -> None:
    """T6 — brand bans emojis/pictograms in visuals; doctor markers are
    plain-text [OK]/[WARN]/[FAIL] so nothing in these files should sit in
    an emoji codepoint range."""
    ranges = ((0x1F000, 0x1FAFF), (0x2600, 0x27BF), (0xFE00, 0xFE0F), (0x2190, 0x21FF))
    for path in (CAPTURE, PREVIEW):
        for ch in path.read_text(encoding="utf-8"):
            cp = ord(ch)
            for lo, hi in ranges:
                assert not (lo <= cp <= hi), f"{path.name} contains pictogram U+{cp:04X}"
