# Copyright 2026 Sumith Ramsookbhai. Licensed under Apache-2.0 (see LICENSE).
"""Tests for the committed marketplace assets (issue #84).

The assets are GENERATED by scripts/generate_marketplace_assets.py and
committed; these tests pin the acceptance criteria without adding any
imaging dependency:

  T1 — assets/icon-512.png is a valid PNG and exactly 512x512 (IHDR parse)
  T2 — icon stays under the repo's 500 KB added-file ceiling
  T3 — assets/preview-doctor.svg is well-formed XML with positive dimensions
  T4 — preview shows REAL doctor output (capture + render agree on content)
  T5 — sanitisation held: no absolute home paths leak into committed assets
  T6 — brand rule: no emoji/pictogram codepoints in the text assets
  T7 — the committed capture (and SVG) advertise the canonical sumo-qa
       version from pyproject.toml — the preview can't ship a stale
       release number
"""

from __future__ import annotations

import re
import shutil
import struct
import subprocess
import sys
from pathlib import Path

if sys.version_info >= (3, 11):
    import tomllib
else:  # pragma: no cover -- 3.10 backport path; covered by py3.10 CI matrix
    import tomli as tomllib


def _find_repo_root() -> Path:
    """Locate source files when mutmut runs tests from its mirror."""
    here = Path(__file__).resolve()
    for candidate in (here.parent, *here.parents):
        if (candidate / "pyproject.toml").exists() and (
            candidate / "scripts" / "generate_marketplace_assets.py"
        ).is_file():
            return candidate
    raise RuntimeError(f"cannot locate repo root from {here}")


REPO_ROOT = _find_repo_root()
ICON = REPO_ROOT / "assets" / "icon-512.png"
CAPTURE = REPO_ROOT / "assets" / "preview-doctor.txt"
PREVIEW = REPO_ROOT / "assets" / "preview-doctor.svg"

_PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"


def _png_dimensions(path: Path) -> tuple[int, int]:
    blob = path.read_bytes()
    assert blob[:8] == _PNG_SIGNATURE, f"{path} lacks a PNG signature"
    assert blob[12:16] == b"IHDR", f"{path} first chunk is not IHDR"
    width, height = struct.unpack(">II", blob[16:24])
    return width, height


def test_icon_is_512_square() -> None:
    """T1 — the marketplace icon is exactly 512x512."""
    assert ICON.is_file(), (
        "assets/icon-512.png missing — run scripts/generate_marketplace_assets.py icon"
    )
    assert _png_dimensions(ICON) == (512, 512)


def test_icon_under_large_file_ceiling() -> None:
    """T2 — stays under the pre-commit check-added-large-files 500 KB cap."""
    assert ICON.stat().st_size < 500 * 1024


def test_preview_svg_declares_dimensions() -> None:
    """T3 — the preview opens with an <svg> root that declares positive
    dimensions. Parsed with a regex, not an XML library: the file is
    repo-generated, and stdlib XML parsers are XXE-prone on principle."""
    text = PREVIEW.read_text(encoding="utf-8")
    match = re.match(r'<svg [^>]*width="(\d+)" height="(\d+)"', text)
    assert match, "preview-doctor.svg does not open with a dimensioned <svg> root"
    width, height = int(match.group(1)), int(match.group(2))
    assert width >= 800, "preview should be presentation-sized"
    assert height > 0
    assert text.rstrip().endswith("</svg>")
    assert "<!ENTITY" not in text and "<!DOCTYPE" not in text


def test_preview_renders_real_doctor_output() -> None:
    """T4 — every doctor check line in the committed capture appears in the
    rendered SVG (the preview is a render of real output, not a mockup)."""
    capture = CAPTURE.read_text(encoding="utf-8")
    svg = PREVIEW.read_text(encoding="utf-8")
    status_lines = [
        line for line in capture.splitlines() if line.startswith(("[OK]", "[WARN]", "[FAIL]"))
    ]
    assert status_lines, "capture has no doctor status lines — refresh via capture mode"
    for line in status_lines:
        check_id = line.split("—")[0].strip()
        assert check_id in svg, f"capture line not rendered: {check_id}"
    assert "Summary:" in capture and "Summary:" in svg


def test_assets_contain_no_machine_paths() -> None:
    """T5 — path sanitisation held (privacy + reproducible regeneration)."""
    for path in (CAPTURE, PREVIEW):
        text = path.read_text(encoding="utf-8")
        assert "/Users/" not in text, f"{path.name} leaks an absolute macOS home path"
        assert "C:\\Users" not in text, f"{path.name} leaks an absolute Windows home path"
        assert "/home/" not in text, f"{path.name} leaks an absolute Linux home path"


def test_text_assets_contain_no_pictograms() -> None:
    """T6 — brand bans emojis/pictograms in visuals; doctor markers are
    plain-text [OK]/[WARN]/[FAIL] so nothing in these files should sit in
    an emoji codepoint range."""
    ranges = ((0x1F000, 0x1FAFF), (0x2600, 0x27BF), (0xFE00, 0xFE0F), (0x2190, 0x21FF))
    for path in (CAPTURE, PREVIEW):
        for ch in path.read_text(encoding="utf-8"):
            cp = ord(ch)
            for lo, hi in ranges:
                assert not (lo <= cp <= hi), f"{path.name} contains pictogram U+{cp:04X}"


def test_committed_capture_advertises_canonical_version() -> None:
    """T7 — the committed preview must not advertise a stale release. Read
    the first line of the committed capture, extract its `sumo-qa X.Y.Z`
    version, and assert it equals `[project].version` in pyproject.toml —
    the canonical source, readable from a bare source checkout. Pure file
    reads — no install required (importlib.metadata would raise
    PackageNotFoundError without one, or false-fail on a stale editable
    install), no shelling out, no regeneration; deterministic everywhere.
    The same version string must also appear in the committed SVG, which
    pins txt/SVG agreement on the version line."""
    with (REPO_ROOT / "pyproject.toml").open("rb") as fh:
        canonical = tomllib.load(fh)["project"]["version"]
    first_line = CAPTURE.read_text(encoding="utf-8").splitlines()[0]
    match = re.search(r"sumo-qa (\d+\.\d+\.\d+)", first_line)
    assert match, f"capture first line lacks a `sumo-qa X.Y.Z` version: {first_line!r}"
    assert match.group(1) == canonical, (
        f"preview-doctor.txt advertises sumo-qa {match.group(1)} but pyproject.toml "
        f"says {canonical} — refresh via "
        f"`scripts/generate_marketplace_assets.py capture`"
    )
    svg = PREVIEW.read_text(encoding="utf-8")
    assert f"sumo-qa {canonical}" in svg, (
        f"preview-doctor.svg does not advertise sumo-qa {canonical} — txt/SVG "
        f"version lines disagree; re-render via "
        f"`scripts/generate_marketplace_assets.py capture`"
    )


def test_version_mode_syncs_release_bump_without_recapturing(tmp_path: Path) -> None:
    """T8 — release automation updates only the captured version and SVG."""
    repo = tmp_path / "repo"
    (repo / "assets").mkdir(parents=True)
    (repo / "scripts").mkdir()
    shutil.copy2(REPO_ROOT / "scripts" / "generate_marketplace_assets.py", repo / "scripts")
    shutil.copy2(CAPTURE, repo / "assets")
    shutil.copy2(PREVIEW, repo / "assets")

    pyproject = (REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8")
    pyproject, count = re.subn(
        r'(\[project\][^\[]*?\nversion\s*=\s*)"[^"]+"',
        r'\1"9.9.9"',
        pyproject,
        count=1,
        flags=re.DOTALL,
    )
    assert count == 1
    (repo / "pyproject.toml").write_text(pyproject, encoding="utf-8")

    before = (repo / "assets" / "preview-doctor.txt").read_text(encoding="utf-8").splitlines()
    subprocess.run(
        [sys.executable, repo / "scripts" / "generate_marketplace_assets.py", "version"],
        check=True,
        cwd=repo,
    )
    after = (repo / "assets" / "preview-doctor.txt").read_text(encoding="utf-8").splitlines()
    svg = (repo / "assets" / "preview-doctor.svg").read_text(encoding="utf-8")

    assert after[0] == re.sub(r"sumo-qa \d+\.\d+\.\d+", "sumo-qa 9.9.9", before[0])
    assert after[1:] == before[1:]
    assert "sumo-qa 9.9.9" in svg


def test_release_workflow_syncs_and_stages_preview_assets() -> None:
    """T9 — release-please cannot leave preview assets at the old version."""
    workflow = (REPO_ROOT / ".github" / "workflows" / "release-please.yml").read_text(
        encoding="utf-8"
    )
    assert "python scripts/generate_marketplace_assets.py version" in workflow
    assert "assets/preview-doctor.txt assets/preview-doctor.svg" in workflow
