from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol


@dataclass(frozen=True)
class LLMResponse:
    content: str
    model: str
    metadata: dict[str, str]


class LLMClient(Protocol):
    def complete(self, system_prompt: str, user_prompt: str) -> LLMResponse:
        """Generate a response for QA tooling."""


class AsyncLLMClient(Protocol):
    async def complete(self, system_prompt: str, user_prompt: str) -> LLMResponse:
        """Generate a response for QA tooling using the host's configured LLM."""


class MockLLMClient:
    """Deterministic client for local development and unit tests.

    Returns no analysis content - the response is an explicit signal that no
    external LLM is configured. Consumers should treat the empty content as
    "rule-based output only" rather than render mock text as if it were analysis.
    """

    model_name = "deterministic-no-llm"

    def complete(self, system_prompt: str, user_prompt: str) -> LLMResponse:
        del system_prompt, user_prompt
        return LLMResponse(
            content="",
            model=self.model_name,
            metadata={
                "mode": "deterministic",
                "external_calls": "false",
                "note": "No external LLM is configured. Output is rule-based only.",
            },
        )


class AsyncMockLLMClient:
    """Async deterministic client - returns the same honest-empty payload as MockLLMClient.

    Used as the fallback when the host does not advertise sampling support
    or when the user opts out via QA_DISABLE_HOST_SAMPLING.
    """

    model_name = "deterministic-no-llm"

    async def complete(self, system_prompt: str, user_prompt: str) -> LLMResponse:
        del system_prompt, user_prompt
        return LLMResponse(
            content="",
            model=self.model_name,
            metadata={
                "mode": "deterministic",
                "external_calls": "false",
                "note": "No external LLM is configured. Output is rule-based only.",
            },
        )


class HostSamplingClient:
    """Async LLM client that delegates to the MCP host via the sampling spec.

    The host (Claude Code, Copilot, Cursor, etc.) decides which model runs the
    completion - whatever the user has configured. The MCP server only supplies
    the QA-discipline system prompt and a guardrailed user prompt.

    If the host does not advertise sampling support, `session.create_message`
    raises and the caller is expected to fall back gracefully.
    """

    model_name = "host-llm-via-sampling"

    def __init__(self, session: object, max_tokens: int = 1024) -> None:
        self._session = session
        self._max_tokens = max_tokens

    async def complete(self, system_prompt: str, user_prompt: str) -> LLMResponse:
        try:
            from mcp.types import SamplingMessage, TextContent
        except ImportError as exc:  # pragma: no cover - mcp SDK is a hard dep
            raise RuntimeError("mcp SDK is required for HostSamplingClient") from exc

        message = SamplingMessage(
            role="user",
            content=TextContent(type="text", text=user_prompt),
        )
        result = await self._session.create_message(
            messages=[message],
            max_tokens=self._max_tokens,
            system_prompt=system_prompt,
        )
        text = ""
        if hasattr(result, "content"):
            content = result.content
            if hasattr(content, "text"):
                text = content.text or ""
            elif isinstance(content, list) and content:
                first = content[0]
                if hasattr(first, "text"):
                    text = first.text or ""
        model_name = getattr(result, "model", self.model_name)
        return LLMResponse(
            content=text,
            model=model_name,
            metadata={
                "mode": "host-sampling",
                "external_calls": "true",
                "note": "Generated by the MCP host's configured LLM via sampling.",
            },
        )


class VertexAIClient:
    """Stub for a future Vertex AI implementation."""

    def __init__(self, project: str | None = None, location: str | None = None, model: str | None = None) -> None:
        self.project = project
        self.location = location or "us-central1"
        self.model = model or "gemini"

    def complete(self, system_prompt: str, user_prompt: str) -> LLMResponse:
        del system_prompt, user_prompt
        raise NotImplementedError(
            "VertexAIClient is a Phase 1 stub. Use MockLLMClient until Vertex AI auth and model policy are configured."
        )
