# Copyright 2026 Sumith Ramsookbhai. Licensed under Apache-2.0 (see LICENSE).
"""Runtime accessor for the canonical plugin metadata snapshot.

The snapshot is generated by `plugin_packaging.plugin_generator` from
`pyproject.toml` and bundled into the wheel at
`sumo_qa/_data/plugin_metadata.json`. This module is the ONLY runtime
reader — every consumer (installer, smoke tests, etc.) goes through
`PluginMetadata.from_bundle()`.

Why a snapshot: `pyproject.toml` lives at the build boundary and is not
inside the installed package. The snapshot bridges canonical-source
and runtime without duplicating fields by hand.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from importlib import resources


@dataclass(frozen=True)
class PluginMetadata:
    name: str
    version: str
    description: str
    license: str
    author: dict
    homepage: str
    repository: str
    display_name: str
    keywords: tuple[str, ...]
    mcp_server_name: str
    mcp_command: str
    mcp_transport: str
    mcp_args: tuple[str, ...]

    @classmethod
    def from_bundle(cls) -> PluginMetadata:
        # Walk into `sumo_qa/_data/plugin_metadata.json` via the parent
        # package's Traversable. Avoids needing `_data` to be a Python
        # subpackage — keeps the bundled-data dir a pure data directory,
        # which matches how `standards/`, `knowledge/`, `skills/`, etc.
        # are shipped (no __init__.py inside).
        data_file = resources.files("sumo_qa") / "_data" / "plugin_metadata.json"
        with data_file.open("r", encoding="utf-8") as fh:
            data = json.load(fh)
        mcp = data["mcp"]
        return cls(
            name=data["name"],
            version=data["version"],
            description=data["description"],
            license=data["license"],
            author=data["author"],
            homepage=data["homepage"],
            repository=data["repository"],
            display_name=data["display_name"],
            keywords=tuple(data["keywords"]),
            mcp_server_name=mcp["server_name"],
            mcp_command=mcp["command"],
            mcp_transport=mcp["transport"],
            mcp_args=tuple(mcp["args"]),
        )
